name: leap-reu-mf-2025
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - xarray
  - jupyterlab
  - dask
  - netcdf4
  - ipykernel
  - scikit-learn
  - scikit-optimize
  - salib
  - pip
  - pip:
      - esem
      - tensorflow
